language: python
python:
  - 3.6
  - 3.7
  - 3.8
sudo: true
before_install:
  - echo "install wkhtmltopdf dependencies"
  - sudo apt-get update
  - sudo apt-get install xfonts-75dpi
  - sudo apt-get install xfonts-base
  - echo "install wkhtmltopdf"
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.5-1.xenial_amd64.deb
  - wkhtmltopdf --version
install:
  - echo "install start"
  - pip install poetry
  - poetry install
  - pip install codecov
  - echo "install end"
script:
  - echo "script start"
  - pytest --cov=seminario
  - flake8 seminario
  - echo "script end"
after_success:
  - codecov
