language: python
python:
  - 3.6
  - 3.7
  - 3.8
sudo: false
before_install:
  - echo '## Installing wkhtmltopdf dependencies'
  - sudo apt-get update -qq
  - sudo apt-get install -y libxrender1 libfontconfig1 zlib1g libfreetype6 libx11-6 libxext6
  - echo '## Installing wkhtmltopdf'
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - export WKHTMLTOPDF_CMD="$PWD/wkhtmltox/bin/wkhtmltopdf"
install:
  - echo "install start"
  - pip install poetry
  - poetry install
  - pip install codecov
  - echo "install end"
script:
  - echo "script start"
  - pytest --cov=seminario
  - flake8 seminario
  - echo "script end"
after_success:
  - codecov
