language: python
python: 3.5
install:
  - echo "install start"
  - pip install -r requirements.txt
  - echo "install end"
before_script:
  - pip install pyyaml
script:
  - echo "script start"
  - sh tests/pytest.sh
  - echo "script end"
