language: python
python: 3.8
install:
  - echo "install start"
  - pip install -r requirements.txt
  - echo "install end"
before_script:
  - pip install flake8
  - pip install pyyaml
script:
  - echo "script start"
  - sh tests/pytest.sh
  - flake8 ./seminario/
  - echo "script end"
